name: Deploy to EC2

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
          
      - name: Build with Gradle
        run: ./gradlew build -x test
        
      - name: List build directory
        run: ls -la build/libs/
        
      - name: Copy JAR file
        run: |
          mkdir -p ~/backend
          cp build/libs/AlbaEase-0.0.1-SNAPSHOT.jar app.jar
          
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/backend
            git checkout develop
            git pull
            docker-compose down
            docker rm -f mysql-container || true
            docker rm -f springapp || true
            docker-compose up -d --build
