name: Deploy to EC2
on:
  push:
    branches: [ "develop" ]  # develop 브랜치와 연결

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user     # ec2-user, ec2 인스턴스 사용자 이름
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
              cd ~/backend  # 정확한 디렉토리 지정
              git checkout develop  # develop 브랜치 명시적 지정
              git pull
              docker-compose down
              docker rm -f mysql-container || true  # 컨테이너가 있으면 제거, 없어도 에러 발생하지 않음
              docker-compose up -d --build
